/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controlador.ControlEventosPrincipal;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.controlObrasArtistasExposicion;

/**
 *
 * @author RozoJ
 */
public class SeccionCRUDArte extends javax.swing.JPanel {
    String user;
    /**
     * Creates new form SeccionCRUDArte
     */
    public SeccionCRUDArte(String user) {
      
    
        initComponents();
        this.user = user;
         setOpaque(false);
        buttonGroup1.add(jCheckBox1);
        buttonGroup1.add(jCheckBox2);
        buttonGroup1.add(jCheckBox3);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        crearbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modificarbtn = new javax.swing.JButton();
        eliminarbtn = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        titulotextfield = new javax.swing.JTextField();
        nombretextfield = new javax.swing.JTextField();
        infoconsulta = new javax.swing.JLabel();
        Comprarbtn = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/Captura de pantalla 2024-05-17 213849.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/Captura de pantalla 2024-05-17 213900.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        crearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/Captura de pantalla 2024-05-17 221645.png"))); // NOI18N
        crearbtn.setBorderPainted(false);
        crearbtn.setContentAreaFilled(false);
        crearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearbtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/tituloimg.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/nombreimg.png"))); // NOI18N

        modificarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/modificarbtn.png"))); // NOI18N
        modificarbtn.setBorderPainted(false);
        modificarbtn.setContentAreaFilled(false);
        modificarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarbtnActionPerformed(evt);
            }
        });

        eliminarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espaciocreativo/img/eliminarbtn.png"))); // NOI18N
        eliminarbtn.setBorderPainted(false);
        eliminarbtn.setContentAreaFilled(false);
        eliminarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnActionPerformed(evt);
            }
        });

        infoconsulta.setBackground(new java.awt.Color(204, 204, 255));
        infoconsulta.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        infoconsulta.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Comprarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Captura de pantalla 2024-05-27 040011.png"))); // NOI18N
        Comprarbtn.setBorderPainted(false);
        Comprarbtn.setContentAreaFilled(false);
        Comprarbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Comprarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombretextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(titulotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eliminarbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificarbtn)
                                .addGap(115, 115, 115)
                                .addComponent(Comprarbtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(15, 15, 15)))
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(crearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(infoconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(14, 14, 14)
                                .addComponent(jCheckBox2)
                                .addGap(13, 13, 13)
                                .addComponent(jCheckBox3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(crearbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(infoconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(titulotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombretextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eliminarbtn)
                        .addComponent(modificarbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Comprarbtn)
                        .addGap(2, 2, 2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearbtnActionPerformed
        if(jCheckBox1.isSelected()){
        PantallaCrearObra pc = new PantallaCrearObra();
        pc.setVisible(true);
        }
        if(jCheckBox2.isSelected()){
            pantallaCrearArtistas ca = new pantallaCrearArtistas();
            ca.setVisible(true);
        }
        if(jCheckBox3.isSelected()){
            PantallaCrearExposicion ce = new PantallaCrearExposicion();
            ce.setVisible(true);
        }
    }//GEN-LAST:event_crearbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(jCheckBox1.isSelected()){
          ControlEventosPrincipal ce = new ControlEventosPrincipal();
          ce.consultaObra(titulotextfield.getText(), nombretextfield.getText(), this);
      }
      if(jCheckBox2.isSelected()){
          ControlEventosPrincipal ce = new ControlEventosPrincipal();
          ce.consultaArtista(nombretextfield.getText(), this);
          
      }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modificarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarbtnActionPerformed
        if(jCheckBox1.isSelected()){
            ModificarObra m = new  ModificarObra(titulotextfield.getText());
            m.setVisible(true);
        }
        if(jCheckBox2.isSelected()){
            ModificarArtista n =  new ModificarArtista(nombretextfield.getText());
            n.setVisible(true);
        }
        if(jCheckBox3.isSelected()){
            ModificarExposicion o =  new ModificarExposicion();
            o.setVisible(true);
        }         
                
    }//GEN-LAST:event_modificarbtnActionPerformed

    private void eliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnActionPerformed
       if(jCheckBox1.isSelected()){
        ControlEventosPrincipal ce = new ControlEventosPrincipal();
        ce.eliminarObraEvento(titulotextfield.getText());
           
           JOptionPane.showMessageDialog(this, "!Obra eliminada!", "Notificación", JOptionPane.INFORMATION_MESSAGE);
       }
        if(jCheckBox2.isSelected()){
            
            ControlEventosPrincipal ce = null;
            ce = new ControlEventosPrincipal();
            ce.eliminarArtistaEvento(nombretextfield.getText());
           
           JOptionPane.showMessageDialog(this, "!Artista eliminado!", "Notificación", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_eliminarbtnActionPerformed

    private void ComprarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarbtnActionPerformed
       
       SeccionRArteComprar sa = new SeccionRArteComprar(user, titulotextfield.getText());
       
        sa.setVisible(true);
        
    }//GEN-LAST:event_ComprarbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprarbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton crearbtn;
    private javax.swing.JButton eliminarbtn;
    private javax.swing.JLabel infoconsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton modificarbtn;
    private javax.swing.JTextField nombretextfield;
    private javax.swing.JTextField titulotextfield;
    // End of variables declaration//GEN-END:variables

  public void mostrarBotones() {
        eliminarbtn.setVisible(true);
        modificarbtn.setVisible(true);
        crearbtn.setVisible(true);
    }
  
      public void ocultarBotones() {
        eliminarbtn.setVisible(false);
        modificarbtn.setVisible(false);
        crearbtn.setVisible(false);
    }
      
          public void setinfoconsulta(String text) {
      
       infoconsulta.setText("<html>" + text + "</html>");
       
        
    }
          
     public String getTituloConsulta(){
         return titulotextfield.getText();
     }
     
      public String getfield2Consulta(){
         return nombretextfield.getText();
     }
     
     public String getInfotxt(){
         return infoconsulta.getText();
     }


}
